version: '3.7'
services:
  frontend:
    container_name: glygen-frontend
    image: glygen-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
networks:
  default:
    external:
      name: ${GLYGEN_NETWORK:-glygen-network}