# Glygen deployment MakeFile

.PHONY: prod beta test dev clean
GLYGEN_NETWORK = glygen-network

network:
	@docker network ls --format='{{ .Name }}' | grep ^${GLYGEN_NETWORK}$$ > /dev/null 2>&1 || docker network create ${GLYGEN_NETWORK};

prod: network
	@docker-compose stop
	@docker-compose rm --force
	@docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --detach --build
	@docker image prune --force

beta: network
	@docker-compose stop
	@docker-compose rm --force
	@docker-compose -f docker-compose.yml -f docker-compose.beta.yml up --detach --build
	@docker image prune --force

test: network
	@docker-compose stop
	@docker-compose rm --force
	@docker-compose -f docker-compose.yml -f docker-compose.test.yml up --detach --build
	@docker image prune --force

dev: network
	@docker-compose stop
	@docker-compose rm --force
	@docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --detach --build
	@docker image prune --force

clean:
	@docker system prune --force
